### ISSUE TITLE
where you load the checkpoint of ViT backbone?

### ISSUE THREAD

**Issue by SHIBOYA** [taoyang1122/adapt-image-models#12]
where to load the checkpoint of base model?  i cannot find where you load the checkpoint of ViT backbone

**Comment by taoyang1122** [comment]
Please refer to https://github.com/taoyang1122/adapt-image-models/blob/main/mmaction/models/backbones/vit_clip.py#L146

**Comment by SHIBOYA** [comment]
thank you very much!
