### ISSUE TITLE
Could you please share the swin transformer model weights on Kinetics 400?

### ISSUE THREAD

**Issue by K0145vin** [taoyang1122/adapt-image-models#13]

**Comment by taoyang1122** [comment]
Sorry, I don't have swin transformer model weights. But I will update the model and training config for swin transformer for reproducing.

**Comment by K0145vin** [comment]
> Sorry, I don't have swin transformer model weights. But I will update the model and training config for swin transformer for reproducing.

Ok, thanks for your reply
