### ISSUE TITLE
How can we freeze the layer?

### ISSUE THREAD

**Issue by VoyageWang** [taoyang1122/adapt-image-models#14]
Hi, I want to know how can we freeze the layer and let them not update parameters? I have a such question after I read your paper.

**Comment by taoyang1122** [comment]
Hi @VoyageWang , you can set param.requires_grad=False. Please refer to https://github.com/taoyang1122/adapt-image-models/blob/main/tools/train.py#L187

**Comment by VoyageWang** [comment]
你好，你的邮件已经被我接受。hello，your email has been recieved. Thank you.
