### ISSUE TITLE
T-MSA and S-MSA

### ISSUE THREAD

**Issue by chaolistat** [taoyang1122/adapt-image-models#16]
Where can I find the codes for T-MSA and S-MSA？Or where did the patch embedding reshape take place?Thanks

**Comment by taoyang1122** [comment]
Please refer to https://github.com/taoyang1122/adapt-image-models/blob/main/mmaction/models/backbones/vit_clip.py#L80.

**Comment by chaolistat** [comment]
thanks very much, but why the only class uses 'ResidualAttentionBlock' says 'Space only'? https://github.com/taoyang1122/adapt-image-models/blob/main/mmaction/models/backbones/vit_clip.py#L199

**Comment by taoyang1122** [comment]
Sorry for the confusion. It is just a comment I forgot to remove when cleaning the codes. You can ignore that. I will update the codes.
