### ISSUE TITLE
why the second dimension is n*b?

### ISSUE THREAD

**Issue by 007invictus** [taoyang1122/adapt-image-models#21]
https://github.com/taoyang1122/adapt-image-models/blob/4da311e4fbe51131190bde64d8f51c2105fc95fd/mmaction/models/backbones/vit_clip.py#L80

**Comment by taoyang1122** [comment]
Hi, it is combining the spatial dimension with the batchsize dimension, and do self-attention on the temporal dimension in the following self-attention layer.

**Comment by 007invictus** [comment]
why not  (b n)* t*d?

**Comment by taoyang1122** [comment]
because the self-attention is applie to the first dimension.

**Comment by 007invictus** [comment]
Thank you for your reply! It turns out I was careless in looking up the API definition.
