### ISSUE TITLE
About training time.

### ISSUE THREAD

**Issue by leexinhao** [taoyang1122/adapt-image-models#23]
In your paper the GPU training time is 15h, which is much smaller than my reproduction (15 x 8 v100 hours）.  do you multipy the numbers of GPUs?
![image](https://github.com/taoyang1122/adapt-image-models/assets/48858574/72a84aed-baf2-4d43-be5b-f77e3fbc02cd)

**Comment by taoyang1122** [comment]
Hi, sorry for the confusion. The time here is the wall-clock time.

**Comment by 007invictus** [comment]
> Hi, sorry for the confusion. The time here is the wall-clock time.

when i test the speed of the kinetics400 ,i use num_frames=8 so the memory is about 10000m.
but my testing time is 24h x 8v100hours,do you know the possible solution of that issue?
