### ISSUE TITLE
About learning rate setting

### ISSUE THREAD

**Issue by hsi-che-lin** [taoyang1122/adapt-image-models#37]
Hello,
In most of the config files (e.g., [this](https://github.com/taoyang1122/adapt-image-models/blob/main/configs/recognition/vit/vitclip_base_diving48.py)), I can see that the argument "lr" of the optimizers are set to 3e-4, and warmup_iters of the lr_config is set to 2.5. Does this mean the learning rate is starting from 0, linearly increases to 3e-4 at 2.5 epoch, and anneals back to 0 at 50 epoch? Do you scale the learning rate based on the batch size?

**Comment by taoyang1122** [comment]
Hi, you understanding about the behavior of learning rate decay is correct. You may want to scale the learning rate based on the batch size. The current learning rate is for batch size 64.
