### ISSUE TITLE
Have the authors tried fine-tuning the parameters of the LayerNorm layer with it turned on? If so, what were the results?

### ISSUE THREAD

**Issue by Changwei-Ouyang** [taoyang1122/adapt-image-models#42]
Have the authors tried fine-tuning the parameters of the LayerNorm layer with it turned on? If so, what were the results?

**Comment by taoyang1122** [comment]
Thanks for your interest. I believe we tried that, but I don't remember the exact results. You could easily try it by simply modifying the codes [here ](https://github.com/taoyang1122/adapt-image-models/blob/main/tools/train.py#L187).
