### ISSUE TITLE
Visualization Experiments

### ISSUE THREAD

**Issue by laohuijiadezhu** [taoyang1122/adapt-image-models#9]
What an effective method. Thank you for sharing. I have a question. I want to try the same visualization, but I don 't know how to do it. Could you teach me how to conduct visualization experiments？
Looking forward to your reply. Thank you.

**Comment by taoyang1122** [comment]
Hi @laohuijiadezhu , thanks for your interest in our work. You may refer to this [repo](https://github.com/jacobgil/vit-explain). Hope it helps.
